"""Add job_offer_id to Survey (final)

Revision ID: b5de88a4ffdd
Revises: 
Create Date: 2025-07-02 13:16:25.631526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5de88a4ffdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_offer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_survey_job_offer_id', 'job_offer', ['job_offer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_constraint('fk_survey_job_offer_id', type_='foreignkey')
        batch_op.drop_column('job_offer_id')

    # ### end Alembic commands ###
